title: Bar Arnon
description: Acoustic Cheesecake
url: http://blog.i3arnon.com
name: Bar Arnon

twitter_account: i3arnon
github_account:  i3arnon
stackoverflow_account: 885318
linkedin_account: bararnon
google_analytics_key: UA-78241106-1
disqus_sitename: i3arnon

gems:
  - jekyll-sitemap

# Theme
highlight_color: '#222'

# seo
image: /assets/img/avatar_big.jpg
logo: /assets/img/barnon-white.png
social:
  links: 
    - http://twitter.com/i3arnon
    - http://linkedin.com/in/bararnon
    # Not actually supported
    - http://github.com/i3arnon
    - http://stackoverflow.com/users/885318

# Handling Reading
safe: true
exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - post-publish-checklist.md
  - README.md
  - Run.cmd
markdown_ext: "md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: <!--more-->

# Outputting
permalink: /:year/:month/:day/:title/
paginate: 10
timezone: UTC