title: Bar Arnon's Blog
url: http://blog.i3arnon.com
description: Acoustic Cheesecake
email: i3arnon@gmail.com

twitter_account: i3arnon
github_account:  i3arnon
stackoverflow_account: 885318

paginate: 5

# Handling Reading
safe: true
exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - README.md
markdown_ext: "md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: <!--more-->

# Outputting
permalink: /:year/:month/:day/:title/
