title: Bar Arnon
description: Acoustic Cheesecake
url: http://blog.i3arnon.com
name: Bar Arnon
logo: /images/barnon-white.png
image: /images/avatar.jpg

gems:
  - jekyll-sitemap

# Changed in _config-development.yml
production: true

# Theme
highlight_color: '#222'

# Handling Reading
safe: true
exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - post-publish-checklist.md
  - README.md
  - Run.cmd
markdown_ext: "md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: <!--more-->

# Outputting
permalink: /:year/:month/:day/:title/
paginate: 10
timezone: UTC