title: Bar Arnon
name: Bar Arnon
url: http://blog.i3arnon.com
description: Acoustic Cheesecake

twitter_account: i3arnon
github_account:  i3arnon
stackoverflow_account: 885318
google_analytics_key: UA-77401642-1
disqus_sitename: i3arnon

highlight_color: '#222'

gems:
  - jekyll-sitemap

# Handling Reading
safe: true
exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - README.md
  - Run.cmd
markdown_ext: "md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: <!--more-->

# Outputting
permalink: /:year/:month/:day/:title/
paginate: 5